package com.desafioMV.desafioMV.exception;

public class  CustomUserNotFoundException  extends RuntimeException{
    
    public  CustomUserNotFoundException(){
        super("Usuario n√£o encontrado no banco de dados");
    }
}
